---
title: "Analysis for dataset 'UR3 CobotOps' "
subtitle: "799DSAN CapStone Project"
author: "Zhen Li"
date: "2024-06-1"
format:
  pdf:
    documentclass: article
    csl: apa.csl
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[L]{Analysis for dataset 'UR3 CobotOps' }
bibliography: references.bib
---


# Introduction

Introduction text

# Buin

The data source is from Tyrovolas,Marios, Aliev,Khurshid, Antonelli,Dario, and Stylios,Chrysostomos. (2024). UR3 CobotOps. UCI Machine Learning Repository. https://doi.org/10.24432/C5J891. [@misc_ur3_cobotops_963].

# data


Variables list

| Variable Name |	Role  |	Type      | Missing Values |
|:--------------|:------|:----------|:--------------:|
|Current_J0    	|Feature|	Continuous|			yes        |
|Temperature_T0	|Feature|	Continuous|			yes        |	
|Current_J1	    |Feature|	Continuous|			yes        |
|Temperature_J1	|Feature|	Continuous|			yes        |
|Current_J2	    |Feature|	Continuous|			yes        |
|Temperature_J2	|Feature|	Continuous|			yes        |
|Current_J3	    |Feature|	Continuous|			yes        |
|Temperature_J3	|Feature|	Continuous|			yes        |
|Current_J4	    |Feature|	Continuous|			yes        |
|Temperature_J4	|Feature|	Continuous|			yes        |
|Current_J5	    |Feature|	Continuous|			yes        |
|Temperature_J5	|Feature|	Continuous|			yes        |
|Speed_J0	      |Feature|	Continuous|			yes        |
|Speed_J1	      |Feature|	Continuous|			yes        |
|Speed_J2	      |Feature|	Continuous|			yes        |
|Speed_J3	      |Feature|	Continuous|			yes        |
|Speed_J4	      |Feature|	Continuous|			yes        |
|Speed_J5	      |Feature|	Continuous|			yes        |
|Tool_current	  |Feature|	Continuous|			yes        |
|cycle	        |Feature|	Integer		|   	no         |
|Robot_ProtectiveStop |Target|Binary|			yes        |
|grip_lost          	|Target|Binary|			no         |

## References

