---
title: "Basic Statistics"
format: 
    html:
      code-fold : true
      code-summary: "Show Code"
warning: false
message: false
---

# advance ggplot

```{r}
library(ggplot2)
library(GGally)
```


## A scatter plot with best-fit lines
```{r}
data(mtcars)
ggplot(mtcars, aes(x=wt, y=mpg)) + 
  geom_point()+ 
  geom_smooth(method="lm", se=FALSE, color="red") + 
  geom_smooth(method="loess", se=FALSE,
            color="blue", linetype="dashed") +
    labs(title = "Basic Scatter Plot of MPG vs. Weight", 
       x = "Car Weight (lbs/1000)",
       y = "Miles Per Gallon")
```


## by cylinder
```{r}
ggplot(mtcars,
       aes(x=wt, y=mpg,
           color=factor(cyl),
           shape=factor(cyl))) +
  geom_point(size=2) +
  geom_smooth(method="lm", se=FALSE) +
  geom_smooth(method="loess", span=4, se=FALSE, linetype="dashed") +
  labs(title = "Scatter Plot of MPG vs. Weight",
       subtitle = "By Number of Cylinders",
       x = "Car Weight (lbs/1000)",
       y = "Miles Per Gallon",
       color = "Number of \nCylinders",
       shape = "Number of \nCylinders") +
  theme_bw()

```

## ggpairs() from GGally package
```{r}
ggpairs(mtcars[c("mpg","disp","drat", "wt")])
```

## Modify the ggpair()
```{r}
diagplots <- function(data, mapping) {
  ggplot(data = data, mapping = mapping) +
    geom_histogram(fill="lightblue", color="black")
  }
lowerplots <- function(data, mapping) {
  ggplot(data = data, mapping = mapping) +
    geom_point(color="darkgrey") +
    geom_smooth(method = "lm", color = "steelblue", se=FALSE) +
    geom_smooth(method="loess", color="red", se=FALSE, linetype="dashed")
  }
upperplots <- function(data, mapping) {
  ggally_cor(data=data, mapping=mapping,
             display_grid=FALSE, size=3.5, color="black")
  }
mytheme <- theme(strip.background = element_blank(),
                 panel.grid = element_blank(),
                 panel.background = element_blank(),
                 panel.border = element_rect(color="grey20", fill=NA))
ggpairs(mtcars,
        columns=c("mpg","disp", "drat", "wt"),
        columnLabels=c("MPG", "Displacement",
                       "R Axle Ratio", "Weight"),
        title = "Scatterplot Matrix with Linear and Loess Fits",
        lower = list(continuous = lowerplots),
        diag = list(continuous = diagplots),
        upper = list(continuous = upperplots)) +
  mytheme
```

